# Generated by Django 4.2 on 2023-04-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('c', 'cafe'), ('r', 'restaurant'), ('p', 'pub')], max_length=1)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=253)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sp', 'sport'), ('tr', 'traveling'), ('pt', 'painting'), ('cg', 'computer_games'), ('sh', 'shopping'), ('ph', 'photo'), ('ms', 'music')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=253)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('city', models.CharField(default='Minsk', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arrangement.users')),
                ('min_bill_value', models.PositiveIntegerField(null=True)),
            ],
            bases=('arrangement.users',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arrangement.users')),
                ('max_spent_value', models.PositiveIntegerField(null=True)),
            ],
            bases=('arrangement.users',),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['age', 'name'], name='arrangement_age_d35502_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name'], name='arrangement_name_9dbcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['-name'], name='arrangement_name_4310b3_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['-age'], name='arrangement_age_e19a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name', '-sex'], name='arrangement_name_198699_idx'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.users'),
        ),
        migrations.AddField(
            model_name='passport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='user',
            field=models.ManyToManyField(to='arrangement.users'),
        ),
        migrations.AddField(
            model_name='establishmentsrating',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments'),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='establishments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments'),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.guest'),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.host'),
        ),
    ]
