# Generated by Django 4.2 on 2023-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_alter_guest_options_alter_host_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='max_spent_value',
            new_name='max_spend_value',
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('b', 'busy')], default='a', max_length=1),
        ),
    ]
