# Generated by Django 4.2 on 2023-05-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0003_rename_max_spent_value_host_max_spend_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_ratings'),
        ),
    ]
